;------------------------------------------------------
; TestPoint configuration/settings file.
;------------------------------------------------------

;------------------------------------------------------
; GPIB section(s).
;       Hardware configuration for GPIB interface boards.
[GPIB0]
io=0x2B8
dma=1   
myaddr=21

;------
; AD,DA section(s).
;       Hardware configuration for A/D,D/A boards.
;       Note: manufacturer=AUTO works with some board vendors
;       (for example, DT and NI).  For other vendors, you will
;       have to manually edit this section - see the A/D setup
;       documentation (file AD.WRI) for more detailed information.
[AD0]
manufacturer=AUTO
[AD1]
manufacturer=AUTO
[AD2]
manufacturer=AUTO
[AD3]
manufacturer=AUTO

;------------------------------------------------------
; DIO section(s).
;       Hardware configuration for digital I/O.
[DIO0]
io=0x700
channels=1

;------------------------------------------------------
; STYLES section.
;    TestPoint application templates and TestStyles for the TestWizard
;
;   TEMPLATES lists the available application wizard template names
[TEMPLATES]
TA=Blank
TB=Acquire & Graph (A/D)
TC=Strip chart (A/D)
TD=Automated testing

;   STYLES lists the available TestStyles by name and path to object
;          stock file.
[STYLES]
S1=Classic (Plain),styles\classic\classic.stk
S2=Brushed Aluminum,styles\alum\alum.stk
S3=High-Tech Plastic,styles\plastic\plastic.stk

;   Sections here for each template list the TST files for that template
;       in each style for which it is available
[TA]
S1=styles\classic\blank.tst
S3=styles\plastic\blank.tst
S2=styles\alum\blank.tst
[TB]
S1=styles\classic\daq.tst
S3=styles\plastic\daq.tst
S2=styles\alum\daq.tst
[TC]
S1=styles\classic\strip.tst
S3=styles\plastic\strip.tst
S2=styles\alum\strip.tst
[TD]
S1=styles\classic\ate.tst
S3=styles\plastic\ate.tst
S2=styles\alum\ate.tst


;------------------------------------------------------
; CONFIG section.
;   TestPoint settings that control execution and display
;   options.

[Config]

;;-------
;; new v6 configuration options....
BGWindow=no     ; if yes, create a full-size background window behind the panel,stock,etc.
                ; to cover up the desktop and other clutter.  Normal mode (BGWindow=no)
                ; creates all the TestPoint editor windows as separate floating windows.
                ;  NOTE: you can set the color of the background window
                ;    by using  BGwindow=#bbggrr    where bb, gg, and rr are
                ;    hexadecimal numbers for the amount of blue, green, and red.
                ;    For example, light gray is   #C0C0C0
                ;  NOTE: you can also avoid clutter in the background by minimizing
                ;   other applications, and optionally turning on the "Active Desktop"
                ;   option in Windows and setting the "Hide icons when the desktop
                ;   is viewed as a web page" option (both of these are in the display
                ;   properties dialog, right-click on the desktop and choose Properties).
editor=new      ; if "old", uses the old v5-style editor window with panel, stock, etc.
                ;  as child windows of the main window... however, you cannot have
                ;  menu bars on a panel in this case within the editor!

;;-------
;;  Language=English        ; language for testpoint editor
                            ; By default, TestPoint uses the Windows language
                            ; if that language is supported.
                            ; UN-COMMENT the above line by removing the 
                            ; semi-colons to override the Windows language
                            ;       (must be in [languages] section below)

GraphBuffer=Yes         ; use offscreen buffer for updating graphs smoothly?
MarkerLimit=4096        ; max # pts in graph trace with markers (above this limit
                        ;  a line-only trace is used)

RedrawLimit=Yes         ; if yes, limit how often the screen gets updated 
                        ; to 20 times per second.  This increases the
                        ; overall speed of applications by eliminating
                        ; unneeded screen accesses. (default is Yes)

MaxPendingEvents=300     ; # of events that can be waiting for each object
                        ;    (0 to 30000)
UIMaxPendingEvents=1    ; # of events waiting for user-input objects
                        ;    (i.e. "typeahead" limit for buttons, etc.)
                        ;    (0 to 10000)
Stack=64                ; Action list stack depth (16 to 512)
MaxObjectWindows=2      ; Maximum number of object-inspection windows
                        ;    (with tabs for settings, actions, etc.)
                        ;    that can remain open at once.  Does not
                        ;    include settings that are open only
                        ;    temporarily.  (1 to 32)
OCXSaveAtRun=Yes        ; Should settings (properties) of OCX objects
                        ;    be saved when switching Edit->Run, and
                        ;    restored when switch back to Edit mode?
                        ;    (In other words, should property changes
                        ;     during Run mode be temporary?)
  ; Settings for drag-and-drop interaction.
  ; These control the operation of pausing over a window while dragging,
  ; to bring it to the front, or to scroll a list.
DragPauseDistance=8     ; Maximum distance the mouse can move, in dots,
                        ;    and still be considered as paused over one
                        ;    location. (4 to 50)
DragPause=1000          ; Time in milliseconds to pause over one place
                        ;    before the window jumps to the front, or
                        ;    scrolling begins. (500 to 10000)
DragScroll=100          ; Time in milliseconds for scroll repeat rate.
                        ;    (100 to 5000)

        ; Arial=Yes     ; This setting, if added, forces TestPoint to
                        ; use the Arial font for its action lists, etc.
                        ; Usually, TestPoint chooses the display font
                        ; automatically. However, some displays have
                        ; a bug which causes gaps in the background
                        ; color on highlighted text - this bug can
                        ; be avoided by using the Arial=Yes setting.

        ; compress=old  ; (new in v5) If this setting is added, runtimes
                        ; are built using the old compression method
                        ; (which does not match the new SETUP program)
                        ; This option should not normally be used.

        ; nodlinxfix=yes ; (new in v4) If added, this skips the code
                        ; which is designed to fix a tasking issue for
                        ; DriverLINX A/D drivers in Windows 2000/xp,
                        ; wherein the drivers are loaded early during
                        ; testpoint startup.  This option should not
                        ; normally be used, but is safe to use if you
                        ; do not use DriverLINX drivers.

        ; lock32=no     ; (new in v5) If added, this disables 32-bit
                        ; task interlocking for some I/O objects such
                        ; as GPIB.  These task locks are needed when
                        ; running multiple TestPoint programs as separate
                        ; win32 processes (which is now the default).

        ; oldidle=yes   ; (new in v5) If added, this disables the new
                        ; idle-time handler, which was changed in v5
                        ; to  allow the system idle process to run,
                        ; and thus not show high cpu usage


;------------------------------------------------------
; International settings.
;
[Intl]
sDecimal=.              ; decimal separator for numbers,
                        ;  used only for clipboard and DDE data
                        ; can be 
                        ;     sDecimal=. 
                        ;     sDecimal=,
                        ;     sDecimal=Windows
                        ; if it is Windows, the control panel international
                        ; setting applies
                        ; (This is appropriate for Microsoft Excel).
sDecimalFile=.          ; separator for File object output of numbers
                        ; (to use comma, requires sDecimal to be set also).

;------------------------------------------------------
; A/D
;
; ADDRIVERS section.
;       List of TestPoint drivers supplied for various A/D manufacturers.
;       Do not edit.
;  NOTE!! - new drivers should be added in file TPAD.INI, not this file!
;
;       AUTO    - automatic board setup driver - works with some brands.
;       Keithley        - Keithley/Metrabyte boards - can use AUTO
;       DT              - Data Translation boards - can use AUTO
;       UEI             - United Electronic Industries boards
;       DAS             - Metrabyte DAS-16 series and compatibles
;       NI              - National Instruments A/D boards - can use AUTO
;       Analogic        - Analogic FAST-series boards
;       ADAC            - ADAC boards
;       Eagle           - Eagle Technologies boards
[ADDRIVERS]
AUTO=TPAUTO.DLL
Keithley=TPKEITH.DLL
DT=TPDT.DLL
UEI=TPUEI.DLL
DAS=TPDAS.DLL
Analogic=TPALOG.DLL
ADAC=TPADAC.DLL
Eagle=TPEAGLE.DLL
NI=TPNI.DLL
; important - leave NI driver last in list for auto-cfg to work correctly

;------------------------------------------------------
; Print preference settings.
;
;    List of object settings to be skipped in "some" settings print mode.
;    To skip all settings for an object, just list its class name.
;    To skip specific settings, use the class name, :, and the setting name.
;    EXACT SPELLING AND UPPER/LOWER CASE ARE SIGNIFICANT.
;
[Print.SkipSettings]
Switch:Style
Switch:Bezel
Switch:Caption
Selector:Style
Selector:Bezel
Selector:Caption
Slider:Bezel
Slider:Caption
Slider:Labels
Data-Entry:Bezel
Data-Entry:Caption 
Indicator:Style
Indicator:Text size (dots)
Indicator:Color 0
Indicator:Label 0
Indicator:Color 1
Indicator:Label 1
Indicator:Text color 0
Indicator:Text color 1
Indicator:Bezel
Indicator:Caption
Display:BG Color
Display:Text Color
Display:Text Size (dots)
Display:Bezel
Display:Caption
Bar:Color
Bar:BG Color
Bar:Bezel
Bar:Caption
Bar:Labels
Grid:Grayed
Grid:Bezel
Grid:Caption
Graph:Plot Area (%)
Graph:Left
Graph:Right
Graph:Top
Graph:Bottom
Graph:BG Color
Graph:Bezel
Graph:Caption
Graph:Trace Number
Graph:Color
Graph:Style
Graph:Width
Graph:Shape
Graph:Size (pts)
Graph:Y Axis
Graph:Axis
Graph:On
Graph:Auto
Graph:From
Graph:To
Graph:Intercept (% full scale)
Graph:Logarithmic
Graph:Title
Graph:Step
Graph:# Minor
Graph:Position
Graph:Major
Graph:Minor
RS232 :Default output term.
RS232 :Default input term.
GPIB:Default output term.
GPIB:Default input term.
GPIB:Bezel
GPIB:Caption
File:Bezel
File:Caption
Label
Picture:Auto-Size
Picture:Stretch
Picture:Caption
Picture:Bezel
Picture:BG Color
Panel:BG Color
BitmapSwitch:bmpname
BitmapSwitch:iconf
OLE:Bezel


;------------------------------------------------------
; Objects section.
;       Used internally by TestPoint for add-on object libraries.
;       Do not edit.
[Objects]
TMOVbx=TPVBX.DLL


;------------------------------------------------------
; MATH section.
;   External math libraries for TestPoint.
;   DO NOT CHANGE THIS SECTION.
[Math]
tpmath1.dll=

;-----------
; LANGUAGES section.
;  Do not change this section.
;  includes both TestPoint language codes like "English", and
;  Windows codes like "enu".
[Languages]
English=tpuseng.dll
enu=tpuseng.dll
eng=tpuseng.dll

;-----------
; Keywords you use for lock/unlock operations.
; Maintained automatically by TestPoint.
[workspace]
tip=115

max=0
objects=0,238,178,812
dataview=-1
stock=0,53,181,181
menubar=0,0,512,48
grid=10,10,0
obj0=178,175,1448,875
obj1=178,425,1448,625
[MRUFiles]
1=C:\EC14\EC315A.tst
2=C:\TESTPT7\examples\RS232.TST
3=C:\TESTPT7\examples\EC315A.tst
4=C:\EC14\EC315.tst
